### ISSUE TITLE
implementing null-safety

### ISSUE THREAD

**Issue by explodus** [flutterchina/dio#1066] opened 2021-03-04 12:56 UTC
after the current flutter engage show/livestream it could be nice that much more packages get null-safety versions

**Comment by kuhnroyal** [comment] 2021-03-04 13:58
Duplicate of #1019, there is already a null-safe preview version available.

**Comment by explodus** [comment] 2021-03-04 14:03
okay, thx, so if source_gen, build and retrofit_generator get also migrated i could update my project to null-safety

**Comment by kuhnroyal** [comment] 2021-03-04 14:17
Feel free to close this if your question is answered.

**Closed** 2021-03-04 14:17 UTC
