### ISSUE TITLE
opt.connectTimeout was ignored.

### ISSUE THREAD

**Issue by sososdk** [flutterchina/dio#500] opened 2019-10-11 05:46 UTC
```
dependencies:
  dio: ^3.0.3
```

I request by `dio.get(url, options: RequestOptions(connectTimeout: 30 * 1000));`, `connectTimeout` is not work.

https://github.com/flutterchina/dio/blob/ec11282471276b3ce6abcbddc9080aebef1e6d79/dio/lib/src/dio.dart#L1063

**Comment by carmas123** [comment] 2019-10-14 09:38
Duplicate of #494

**Comment by wendux** [comment] 2019-10-29 08:49
Fixed at v3.0.4

**Closed by wendux** 2019-10-29 08:49 UTC
