### ISSUE TITLE
 You cannot set both contentType param and a content-type header    this question?

### ISSUE THREAD

**Issue by lorenzuss** [flutterchina/dio#1133] opened 2021-04-17 11:35 UTC
E/flutter (10637): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:dio/src/options.dart': Failed assertion: line 593 pos 7: '!(contentType != null && contentTypeInHeader)': You cannot set both contentType param and a content-type header
E/flutter (10637): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (10637): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (10637): #2      new _RequestConfig (package:dio/src/options.dart:593:7)
E/flutter (10637): #3      new _BaseOptions&_RequestConfig&OptionsMixin (package:dio/src/options.dart)
E/flutter (10637): #4      new BaseOptions (package:dio/src/options.dart:102:8)
E/flutter (10637): #5      BaseOptions.copyWith (package:dio/src/options.dart:145:12)
E/flutter (10637): #6      Http.init (package:aldedu/http/http.dart:83:31)
E/flutter (10637): #7      HttpUtils.init (package:aldedu/http/http_utils.dart:12:12)
E/flutter (10637): #8      main (package:aldedu/main.dart:13:13)
E/flutter (10637): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
E/flutter (10637): #10     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (10637): #11     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10637): #12     _runZoned (dart:async/zone.dart:1788:10)
E/flutter (10637): #13     runZonedGuarded (dart:async/zone.dart:1776:12)
E/flutter (10637): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
E/flutter (10637): #15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (10637): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (10637):

**Comment by weichongchong** [comment] 2021-04-22 03:57
I meet the same issues

**Comment by Ucoon** [comment] 2021-04-28 00:44
I meet the same issues

**Comment by JoseGeorges8** [comment] 2021-04-28 15:20
Same here. This started happening after upgrading to 4.0.0...

**Comment by greymag** [comment] 2021-05-04 12:39
The problem is that when you first create `BaseOptions`, the default value for `contentType` is used if it's `null`:

```dart
this.contentType = contentType ?? Headers.jsonContentType;
```

And in the setter the content of `_headers` are updated:

```dart
  set contentType(String? contentType) {
    if (contentType != null) {
      _headers[Headers.contentTypeHeader] =
          _defaultContentType = contentType.trim();
    } else {
      _defaultContentType = null;
      _headers.remove(Headers.contentTypeHeader);
    }
  }
```

So **after** creation we have both `contentType = application/json; charset=utf-8` and key `content-type` in `headers` with the same value.

Now, if you call `copyWith()`, `BaseOptions` are created with not null `contentType` param and a `content-type` in `headers` which leads to the assertion error.

### How to fix

Like a quick fix in your code you can remove `content-type` from header when calling `copyWith()`. Like this:

```dart
options.copyWith(
  headers: Map.from(options.headers)
    ..remove(Headers.contentTypeHeader),
);
```

But I think this behaviour should be fixed in the package for sure.

**Comment by sahilkis** [comment] 2021-05-27 05:40
thank you greymag, it is working for me

**Comment by narumishi** [comment] 2021-06-15 00:31
If `contentType` and content-type in `headers` are both provided and **identical**, the assert statement should pass.

**Comment by WilliamCunhaCardoso** [comment] 2021-07-09 20:00
Any news about it? It is being very painful

**Comment by greymag** [comment] 2021-08-21 07:43
The problem is still relevant

**Closed** 2021-11-29 04:12 UTC
